homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret my_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret my_timezone
  customize: !include customize.yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

api:

#Utilizing haaska for Alexa control of Home Assitant
alexa:
  smart_home:

http:
  base_url: !secret base_url
  ssl_certificate: /config/fullchain.pem
  ssl_key: /config/privkey.pem

frontend:
  themes: !include_dir_merge_named themes



sensor:
  # Weather prediction
  - platform: yr
  - platform: template
    sensors:
      octoprint_time_elapsed_format:
        friendly_name: 'Printing Time Elapsed'
        value_template: "{{ states('sensor.ender3_time_elapsed') | int | timestamp_custom('%H:%M:%S', 0) }}"

      octoprint_time_remaining_format:
        friendly_name: 'Printing Time Remaining'
        value_template: "{{ states('sensor.ender3_time_remaining') | int |timestamp_custom('%H:%M:%S', 0) }}"


# Text to speech
tts:
  - platform: google_translate

#Used to control and monitor Creality Ender3 Pro 3D Printer via RaspberryPi 3B+
octoprint:
  host: !secret octo_host
  api_key: !secret octo_api_key
  name: Ender3
  number_of_tools: 1
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'
      - 'Temperatures'

#Pi cam attached to same RaspberryPi 3B+ running Octoprint
camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret camera_still_image_url
    mjpeg_url: !secret camera_mjpeg_url

#DNS ad blocker being ran on a Pi Zero
pi_hole:
  - host: !secret pi_hole_host


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scene.yaml
