#Device is a Gosund-KS2 smart switch

esphome:
  name: garage_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gym Light Fallback Hotspot"
    password: ""

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    name: Gym Light
    pin:
      number: GPIO0
      inverted: true
    on_press:
      - switch.toggle: relay



switch:
  # Switch to toggle the relay
  - platform: gpio
    id: relay
    name: Gym Light Switch
    pin: GPIO14
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  # Relay state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO1
      inverted: true

light:
  # Relay state light
  - platform: monochromatic
    output: state_led
    id: led

# Uses the red LED as a status indicator
status_led:
  pin:
    number: GPIO16
    inverted: true
