#Device is a D1 Mini utilizing a IR transmitting LED to control a Sony TV and a JBL Sound Bar.
#Added a display that pulls temp and humidity from another sensor in the garage and display will only turn on when the gym light is on.

esphome:
  name: garage_tv
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
    #static_ip: !secret garage_tv_ip
    #gateway: !secret gateway
    #subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Tv Fallback Hotspot"
    password: "NAOmAitH5PUj"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


remote_transmitter:
  pin: D6
  carrier_duty_percent: 50%

time:
  - platform: homeassistant
    id: esptime
    timezone: America/Phoenix

sensor:
  - platform: homeassistant
    id: gym_temperature
    entity_id: sensor.garage_temperature_2
    internal: true

  - platform: homeassistant
    id: gym_humidity
    entity_id: sensor.garage_humidity
    internal: false

switch:
  - platform: template
    name: "TV Power"
    id: "tv_power"
    icon: mdi:power
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0xA90
        nbits: 12
        repeat:
          times: 3
    turn_off_action:
      remote_transmitter.transmit_sony:
        data: 0xA90
        nbits: 12
        repeat:
          times: 3
  - platform: template
    name: "Soundbar Power"
    id: "soundbar_power"
    icon: mdi:power
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x212E
        command: 0xFF00
        repeat:
          times: 3
    turn_off_action:
      remote_transmitter.transmit_nec:
        address: 0x212E
        command: 0xFF00
        repeat:
          times: 3
  - platform: template
    name: "Soundbar Source"
    icon: mdi:import
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x10E
        command: 0x9D62
  - platform: template
    name: "Soundbar Volume Up"
    icon: mdi:volume-plus
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x10E
        command: 0xE31C
  - platform: template
    name: "Soundbar Volume Down"
    icon: mdi:volume-minus
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x10E
        command: 0x13EC
  - platform: template
    name: "Soundbar Bass Up"
    icon: mdi:volume-plus
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x10E
        command: 0x37C8
  - platform: template
    name: "Soundbar Bass Down"
    icon: mdi:volume-minus
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x10E
        command: 0xB748

binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_on: tv_power
        - delay: 500ms
        - switch.turn_on: soundbar_power
      
  - platform: homeassistant
    id: gym_switch
    entity_id: switch.gym_light_switch
    internal: true

i2c:
  sda: D1
  scl: D2
  scan: false

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    #reset_pin: D3
    #address: 0x3C
    lambda: |-
      
      if (id(gym_switch).state) {
        // Print "Legendarily-Epic Gym" in top center.
        it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "Legendarily-Epic Gym");
  
        // Print time in HH:MM format
        it.strftime(0, 60, id(font2), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());
  
        // Print inside temperature (from homeassistant sensor)
        if (id(gym_temperature).has_state()) {
          it.printf(127, 23, id(font3), TextAlign::TOP_RIGHT , "%.1f°", id(gym_temperature).state);
        }
  
        // Print outside temperature (from homeassistant sensor)
        if (id(gym_humidity).has_state()) {
          it.printf(127, 60, id(font3), TextAlign::BASELINE_RIGHT , "%.1f%%", id(gym_humidity).state);
        }
      }
font:
  - file: 'Arial.ttf'
    id: font1
    size: 10

  - file: 'Impact.ttf'
    id: font2
    size: 42

  - file: 'Arial.ttf'
    id: font3
    size: 12
