#Device is a Sonoff S31

esphome:
  name: kitchen_plug
  platform: ESP8266
  board: esp8285
  #arduino_version: 2.4.2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Plug Fallback Hotspot"
    password: "xzgTnJO0MDbw"

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Kitchen Plug Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Kitchen Plug Status"

switch:
  - platform: gpio
    name: "Kitchen Plug Switch"
    pin: GPIO12
    id: relay
    icon: mdi:lightbulb

sensor:
  - platform: wifi_signal
    name: "Kitchen Plug WiFi Signal"
    update_interval: 10s
  - platform: cse7766
    current:
      name: "Kitchen Plug Current"
    voltage:
      name: "Kitchen Plug Voltage"
    power:
      name: "Kitchen Plug Power"

status_led:
  pin:
    number: GPIO13
#    inverted: true